[2025-06-27T21:36:15.463Z] info: kubernetes.yaml was copied to the config folder
[2025-06-27T21:46:32.555Z] info: docker.yaml was copied to the config folder
[2025-06-27T21:46:32.557Z] info: services.yaml was copied to the config folder
[2025-06-27T21:46:32.559Z] info: bookmarks.yaml was copied to the config folder
[2025-06-27T21:46:32.560Z] info: widgets.yaml was copied to the config folder
[2025-06-27T21:46:32.561Z] info: custom.css was copied to the config folder
[2025-06-27T21:46:32.562Z] info: custom.js was copied to the config folder
[2025-06-27T22:09:58.362Z] warn: <service-helpers> Error parsing service "Pihole" from config. Ensure required fields are present.
[2025-06-27T22:09:58.365Z] warn: <service-helpers> Error parsing service "Pihole" from config. Ensure required fields are present.
[2025-06-27T22:09:58.722Z] warn: <service-helpers> Error parsing service "Pihole" from config. Ensure required fields are present.
[2025-06-27T22:09:58.840Z] warn: <service-helpers> Error parsing service "Pihole" from config. Ensure required fields are present.
[2025-06-27T22:10:08.204Z] warn: <service-helpers> Error parsing service "Pihole" from config. Ensure required fields are present.
[2025-06-27T22:20:15.979Z] error: <piholeProxyHandler> Failed to login to Pi-Hole API, status: 400
[2025-06-27T22:21:08.041Z] error: <httpProxy> Error calling https://192.168.0.133/admin/api.php...
[2025-06-27T22:21:08.051Z] error: <httpProxy> [
  500,
  Error: connect ECONNREFUSED 192.168.0.133:443
      at <unknown> (Error: connect ECONNREFUSED 192.168.0.133:443) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '192.168.0.133',
    port: 443
  }
]
[2025-06-27T22:21:08.245Z] error: <httpProxy> Error calling https://192.168.0.133/admin/api.php...
[2025-06-27T22:21:08.248Z] error: <httpProxy> [
  500,
  Error: connect ECONNREFUSED 192.168.0.133:443
      at <unknown> (Error: connect ECONNREFUSED 192.168.0.133:443) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '192.168.0.133',
    port: 443
  }
]
[2025-06-27T22:23:26.356Z] error: undefined
[2025-06-27T22:23:26.361Z] error: TypeError: Invalid URL
    at new URL (node:internal/url:818:25)
    at d (/app/.next/server/pages/api/releases.js:1:5196)
    at y (/app/.next/server/pages/api/services/proxy.js:45:68429)
    at async X (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:18441)
    at async z.render (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:19237)
    at async NextNodeServer.runApi (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:671:9)
    at async NextNodeServer.handleCatchallRenderRequest (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:302:37)
    at async NextNodeServer.handleRequestImpl (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:899:17)
    at async invokeRender (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:237:21)
    at async handleRequest (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:428:24)
[2025-06-27T22:23:26.418Z] error: undefined
[2025-06-27T22:23:26.421Z] error: TypeError: Invalid URL
    at new URL (node:internal/url:818:25)
    at d (/app/.next/server/pages/api/releases.js:1:5196)
    at y (/app/.next/server/pages/api/services/proxy.js:45:68429)
    at async X (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:18441)
    at async z.render (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:19237)
    at async NextNodeServer.runApi (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:671:9)
    at async NextNodeServer.handleCatchallRenderRequest (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:302:37)
    at async NextNodeServer.handleRequestImpl (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:899:17)
    at async invokeRender (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:237:21)
    at async handleRequest (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:428:24)
[2025-06-27T22:23:30.467Z] error: undefined
[2025-06-27T22:23:30.469Z] error: TypeError: Invalid URL
    at new URL (node:internal/url:818:25)
    at d (/app/.next/server/pages/api/releases.js:1:5196)
    at y (/app/.next/server/pages/api/services/proxy.js:45:68429)
    at async X (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:18441)
    at async z.render (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:19237)
    at async NextNodeServer.runApi (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:671:9)
    at async NextNodeServer.handleCatchallRenderRequest (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:302:37)
    at async NextNodeServer.handleRequestImpl (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:899:17)
    at async invokeRender (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:237:21)
    at async handleRequest (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:428:24)
[2025-06-27T22:23:40.504Z] error: undefined
[2025-06-27T22:23:40.506Z] error: TypeError: Invalid URL
    at new URL (node:internal/url:818:25)
    at d (/app/.next/server/pages/api/releases.js:1:5196)
    at y (/app/.next/server/pages/api/services/proxy.js:45:68429)
    at async X (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:18441)
    at async z.render (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:19237)
    at async NextNodeServer.runApi (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:671:9)
    at async NextNodeServer.handleCatchallRenderRequest (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:302:37)
    at async NextNodeServer.handleRequestImpl (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:899:17)
    at async invokeRender (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:237:21)
    at async handleRequest (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:428:24)
[2025-06-27T22:23:41.471Z] error: <httpProxy> Error calling http://192.168.0.133:8443/admin/api.php...
[2025-06-27T22:23:41.472Z] error: <httpProxy> [ 500, [Error: socket hang up] { code: 'ECONNRESET' } ]
[2025-06-27T22:23:41.651Z] error: <httpProxy> Error calling http://192.168.0.133:8443/admin/api.php...
[2025-06-27T22:23:41.652Z] error: <httpProxy> [ 500, [Error: socket hang up] { code: 'ECONNRESET' } ]
[2025-06-27T22:25:23.343Z] error: <httpProxy> Error calling http://192.168.0.133:22070/status...
[2025-06-27T22:25:23.344Z] error: <httpProxy> [
  500,
  Error: connect ECONNREFUSED 192.168.0.133:22070
      at <unknown> (Error: connect ECONNREFUSED 192.168.0.133:22070) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '192.168.0.133',
    port: 22070
  }
]
[2025-06-27T22:25:23.569Z] error: <httpProxy> Error calling http://192.168.0.133:22070/status...
[2025-06-27T22:25:23.570Z] error: <httpProxy> [
  500,
  Error: connect ECONNREFUSED 192.168.0.133:22070
      at <unknown> (Error: connect ECONNREFUSED 192.168.0.133:22070) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '192.168.0.133',
    port: 22070
  }
]
[2025-06-27T22:25:35.285Z] error: <httpProxy> Error calling http://192.168.0.133:22070/status...
[2025-06-27T22:25:35.285Z] error: <httpProxy> [
  500,
  Error: connect ECONNREFUSED 192.168.0.133:22070
      at <unknown> (Error: connect ECONNREFUSED 192.168.0.133:22070) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '192.168.0.133',
    port: 22070
  }
]
[2025-06-27T22:28:21.515Z] error: Failed to load widgets, please check widgets.yaml for errors or remove example entries.
[2025-06-27T22:28:21.516Z] error: duplicated mapping key (9:5)

  6 |     cpu: true
  7 |     memory: true
  8 |     disk: /
  9 |     disk: /mnt/hd1/
----------^
 10 | 
 11 | - search:
[2025-06-27T22:28:21.532Z] error: Failed to load widgets, please check widgets.yaml for errors or remove example entries.
[2025-06-27T22:28:21.532Z] error: duplicated mapping key (9:5)

  6 |     cpu: true
  7 |     memory: true
  8 |     disk: /
  9 |     disk: /mnt/hd1/
----------^
 10 | 
 11 | - search:
[2025-06-27T22:28:21.745Z] error: Failed to load widgets, please check widgets.yaml for errors or remove example entries.
[2025-06-27T22:28:21.745Z] error: duplicated mapping key (9:5)

  6 |     cpu: true
  7 |     memory: true
  8 |     disk: /
  9 |     disk: /mnt/hd1/
----------^
 10 | 
 11 | - search:
[2025-06-27T22:29:31.636Z] error: Failed to load widgets, please check widgets.yaml for errors or remove example entries.
[2025-06-27T22:29:31.636Z] error: duplicated mapping key (9:5)

  6 |     cpu: true
  7 |     memory: true
  8 |     disk: /
  9 |     disk: /mnt/hd1
----------^
 10 | 
 11 | - search:
[2025-06-27T22:29:31.672Z] error: Failed to load widgets, please check widgets.yaml for errors or remove example entries.
[2025-06-27T22:29:31.672Z] error: duplicated mapping key (9:5)

  6 |     cpu: true
  7 |     memory: true
  8 |     disk: /
  9 |     disk: /mnt/hd1
----------^
 10 | 
 11 | - search:
[2025-06-27T22:29:31.820Z] error: Failed to load widgets, please check widgets.yaml for errors or remove example entries.
[2025-06-27T22:29:31.820Z] error: duplicated mapping key (9:5)

  6 |     cpu: true
  7 |     memory: true
  8 |     disk: /
  9 |     disk: /mnt/hd1
----------^
 10 | 
 11 | - search:
[2025-06-27T22:29:37.498Z] error: Failed to load widgets, please check widgets.yaml for errors or remove example entries.
[2025-06-27T22:29:37.498Z] error: duplicated mapping key (9:5)

  6 |     cpu: true
  7 |     memory: true
  8 |     disk: /
  9 |     disk: /mnt/hd1
----------^
 10 | 
 11 | - search:
[2025-06-27T22:29:38.069Z] error: Failed to load widgets, please check widgets.yaml for errors or remove example entries.
[2025-06-27T22:29:38.070Z] error: duplicated mapping key (9:5)

  6 |     cpu: true
  7 |     memory: true
  8 |     disk: /
  9 |     disk: /mnt/hd1
----------^
 10 | 
 11 | - search:
[2025-06-27T22:59:03.344Z] error: Failed to load widgets, please check widgets.yaml for errors or remove example entries.
[2025-06-27T22:59:03.345Z] error: bad indentation of a mapping entry (13:9)

 10 |       - /
 11 | - resources:
 12 |   label: Storage
 13 |     disk:
--------------^
 14 |       - /mnt/hd1
 15 | 
[2025-06-27T22:59:03.356Z] error: Failed to load widgets, please check widgets.yaml for errors or remove example entries.
[2025-06-27T22:59:03.356Z] error: bad indentation of a mapping entry (13:9)

 10 |       - /
 11 | - resources:
 12 |   label: Storage
 13 |     disk:
--------------^
 14 |       - /mnt/hd1
 15 | 
[2025-06-27T22:59:03.532Z] error: Failed to load widgets, please check widgets.yaml for errors or remove example entries.
[2025-06-27T22:59:03.532Z] error: bad indentation of a mapping entry (13:9)

 10 |       - /
 11 | - resources:
 12 |   label: Storage
 13 |     disk:
--------------^
 14 |       - /mnt/hd1
 15 | 
[2025-06-27T23:05:53.455Z] error: undefined
[2025-06-27T23:05:53.464Z] error: TypeError: Invalid URL
    at new URL (node:internal/url:818:25)
    at d (/app/.next/server/pages/index.js:4:85636)
    at Wc (/app/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
    at Zc (/app/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
    at Z (/app/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
    at $c (/app/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
    at bd (/app/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:77:404)
    at Z (/app/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:217)
    at $c (/app/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
    at Zc (/app/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:71:145)
[2025-06-27T23:05:53.480Z] error: TypeError: Invalid URL
    at new URL (node:internal/url:818:25)
    at d (/app/.next/server/pages/index.js:4:85636)
    at Wc (/app/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
    at Zc (/app/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
    at Z (/app/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
    at $c (/app/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
    at bd (/app/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:77:404)
    at Z (/app/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:217)
    at $c (/app/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
    at Zc (/app/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:71:145)
[2025-06-27T23:13:04.923Z] error: undefined
[2025-06-27T23:13:04.927Z] error: TypeError: Invalid URL
    at new URL (node:internal/url:818:25)
    at d (/app/.next/server/pages/index.js:4:85636)
    at Wc (/app/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
    at Zc (/app/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
    at Z (/app/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
    at $c (/app/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
    at bd (/app/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:77:404)
    at Z (/app/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:217)
    at $c (/app/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
    at Zc (/app/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:71:145)
[2025-06-27T23:13:04.940Z] error: TypeError: Invalid URL
    at new URL (node:internal/url:818:25)
    at d (/app/.next/server/pages/index.js:4:85636)
    at Wc (/app/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
    at Zc (/app/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
    at Z (/app/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
    at $c (/app/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
    at bd (/app/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:77:404)
    at Z (/app/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:217)
    at $c (/app/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
    at Zc (/app/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:71:145)
[2025-06-28T16:20:23.248Z] error: <piholeProxyHandler> Failed to login to Pi-Hole API, status: 404
[2025-06-28T16:20:23.537Z] error: <piholeProxyHandler> Failed to login to Pi-Hole API, status: 404
[2025-06-28T16:20:33.721Z] error: <piholeProxyHandler> Failed to login to Pi-Hole API, status: 401
[2025-06-28T16:20:49.512Z] error: <piholeProxyHandler> Failed to login to Pi-Hole API, status: 401
[2025-06-28T16:20:49.728Z] error: <piholeProxyHandler> Failed to login to Pi-Hole API, status: 401
[2025-06-29T10:32:53.152Z] error: undefined
[2025-06-29T10:32:53.162Z] error: TypeError: Invalid URL
    at new URL (node:internal/url:818:25)
    at y (/app/.next/server/pages/api/services/proxy.js:45:14628)
    at async X (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:18441)
    at async z.render (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:19237)
    at async NextNodeServer.runApi (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:671:9)
    at async NextNodeServer.handleCatchallRenderRequest (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:302:37)
    at async NextNodeServer.handleRequestImpl (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:899:17)
    at async invokeRender (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:237:21)
    at async handleRequest (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:428:24)
    at async requestHandlerImpl (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:452:13)
[2025-06-29T10:33:03.135Z] error: undefined
[2025-06-29T10:33:03.139Z] error: TypeError: Invalid URL
    at new URL (node:internal/url:818:25)
    at y (/app/.next/server/pages/api/services/proxy.js:45:14628)
    at async X (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:18441)
    at async z.render (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:19237)
    at async NextNodeServer.runApi (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:671:9)
    at async NextNodeServer.handleCatchallRenderRequest (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:302:37)
    at async NextNodeServer.handleRequestImpl (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:899:17)
    at async invokeRender (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:237:21)
    at async handleRequest (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:428:24)
    at async requestHandlerImpl (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:452:13)
[2025-06-29T10:33:03.163Z] error: undefined
[2025-06-29T10:33:03.166Z] error: TypeError: Invalid URL
    at new URL (node:internal/url:818:25)
    at y (/app/.next/server/pages/api/services/proxy.js:45:14628)
    at async X (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:18441)
    at async z.render (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:19237)
    at async NextNodeServer.runApi (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:671:9)
    at async NextNodeServer.handleCatchallRenderRequest (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:302:37)
    at async NextNodeServer.handleRequestImpl (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:899:17)
    at async invokeRender (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:237:21)
    at async handleRequest (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:428:24)
    at async requestHandlerImpl (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:452:13)
[2025-06-29T10:33:08.826Z] error: undefined
[2025-06-29T10:33:08.830Z] error: TypeError: Invalid URL
    at new URL (node:internal/url:818:25)
    at y (/app/.next/server/pages/api/services/proxy.js:45:14628)
    at async X (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:18441)
    at async z.render (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:19237)
    at async NextNodeServer.runApi (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:671:9)
    at async NextNodeServer.handleCatchallRenderRequest (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:302:37)
    at async NextNodeServer.handleRequestImpl (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:899:17)
    at async invokeRender (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:237:21)
    at async handleRequest (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:428:24)
    at async requestHandlerImpl (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:452:13)
[2025-06-29T10:33:28.824Z] error: undefined
[2025-06-29T10:33:28.826Z] error: TypeError: Invalid URL
    at new URL (node:internal/url:818:25)
    at y (/app/.next/server/pages/api/services/proxy.js:45:14628)
    at async X (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:18441)
    at async z.render (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:19237)
    at async NextNodeServer.runApi (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:671:9)
    at async NextNodeServer.handleCatchallRenderRequest (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:302:37)
    at async NextNodeServer.handleRequestImpl (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:899:17)
    at async invokeRender (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:237:21)
    at async handleRequest (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:428:24)
    at async requestHandlerImpl (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:452:13)
[2025-06-29T10:33:32.523Z] error: undefined
[2025-06-29T10:33:32.525Z] error: TypeError: Invalid URL
    at new URL (node:internal/url:818:25)
    at y (/app/.next/server/pages/api/services/proxy.js:45:14628)
    at async X (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:18441)
    at async z.render (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:19237)
    at async NextNodeServer.runApi (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:671:9)
    at async NextNodeServer.handleCatchallRenderRequest (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:302:37)
    at async NextNodeServer.handleRequestImpl (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:899:17)
    at async invokeRender (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:237:21)
    at async handleRequest (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:428:24)
    at async requestHandlerImpl (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:452:13)
[2025-06-29T10:33:42.536Z] error: undefined
[2025-06-29T10:33:42.538Z] error: TypeError: Invalid URL
    at new URL (node:internal/url:818:25)
    at y (/app/.next/server/pages/api/services/proxy.js:45:14628)
    at async X (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:18441)
    at async z.render (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:19237)
    at async NextNodeServer.runApi (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:671:9)
    at async NextNodeServer.handleCatchallRenderRequest (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:302:37)
    at async NextNodeServer.handleRequestImpl (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:899:17)
    at async invokeRender (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:237:21)
    at async handleRequest (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:428:24)
    at async requestHandlerImpl (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:452:13)
[2025-06-29T10:33:46.489Z] error: undefined
[2025-06-29T10:33:46.491Z] error: TypeError: Invalid URL
    at new URL (node:internal/url:818:25)
    at y (/app/.next/server/pages/api/services/proxy.js:45:14628)
    at async X (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:18441)
    at async z.render (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:19237)
    at async NextNodeServer.runApi (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:671:9)
    at async NextNodeServer.handleCatchallRenderRequest (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:302:37)
    at async NextNodeServer.handleRequestImpl (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:899:17)
    at async invokeRender (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:237:21)
    at async handleRequest (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:428:24)
    at async requestHandlerImpl (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:452:13)
[2025-06-29T10:33:51.815Z] error: undefined
[2025-06-29T10:33:51.817Z] error: TypeError: Invalid URL
    at new URL (node:internal/url:818:25)
    at y (/app/.next/server/pages/api/services/proxy.js:45:14628)
    at async X (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:18441)
    at async z.render (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:19237)
    at async NextNodeServer.runApi (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:671:9)
    at async NextNodeServer.handleCatchallRenderRequest (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:302:37)
    at async NextNodeServer.handleRequestImpl (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:899:17)
    at async invokeRender (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:237:21)
    at async handleRequest (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:428:24)
    at async requestHandlerImpl (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:452:13)
[2025-06-29T10:33:58.387Z] error: undefined
[2025-06-29T10:33:58.389Z] error: TypeError: Invalid URL
    at new URL (node:internal/url:818:25)
    at y (/app/.next/server/pages/api/services/proxy.js:45:14628)
    at async X (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:18441)
    at async z.render (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:19237)
    at async NextNodeServer.runApi (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:671:9)
    at async NextNodeServer.handleCatchallRenderRequest (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:302:37)
    at async NextNodeServer.handleRequestImpl (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:899:17)
    at async invokeRender (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:237:21)
    at async handleRequest (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:428:24)
    at async requestHandlerImpl (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:452:13)
[2025-06-29T10:34:02.561Z] error: undefined
[2025-06-29T10:34:02.563Z] error: TypeError: Invalid URL
    at new URL (node:internal/url:818:25)
    at y (/app/.next/server/pages/api/services/proxy.js:45:14628)
    at async X (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:18441)
    at async z.render (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:19237)
    at async NextNodeServer.runApi (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:671:9)
    at async NextNodeServer.handleCatchallRenderRequest (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:302:37)
    at async NextNodeServer.handleRequestImpl (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:899:17)
    at async invokeRender (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:237:21)
    at async handleRequest (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:428:24)
    at async requestHandlerImpl (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:452:13)
[2025-06-29T10:34:05.342Z] error: undefined
[2025-06-29T10:34:05.344Z] error: TypeError: Invalid URL
    at new URL (node:internal/url:818:25)
    at y (/app/.next/server/pages/api/services/proxy.js:45:14628)
    at async X (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:18441)
    at async z.render (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:19237)
    at async NextNodeServer.runApi (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:671:9)
    at async NextNodeServer.handleCatchallRenderRequest (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:302:37)
    at async NextNodeServer.handleRequestImpl (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:899:17)
    at async invokeRender (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:237:21)
    at async handleRequest (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:428:24)
    at async requestHandlerImpl (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:452:13)
[2025-06-29T10:34:08.398Z] error: undefined
[2025-06-29T10:34:08.399Z] error: TypeError: Invalid URL
    at new URL (node:internal/url:818:25)
    at y (/app/.next/server/pages/api/services/proxy.js:45:14628)
    at async X (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:18441)
    at async z.render (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:19237)
    at async NextNodeServer.runApi (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:671:9)
    at async NextNodeServer.handleCatchallRenderRequest (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:302:37)
    at async NextNodeServer.handleRequestImpl (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:899:17)
    at async invokeRender (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:237:21)
    at async handleRequest (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:428:24)
    at async requestHandlerImpl (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:452:13)
[2025-06-29T10:34:10.355Z] error: undefined
[2025-06-29T10:34:10.356Z] error: TypeError: Invalid URL
    at new URL (node:internal/url:818:25)
    at y (/app/.next/server/pages/api/services/proxy.js:45:14628)
    at async X (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:18441)
    at async z.render (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:19237)
    at async NextNodeServer.runApi (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:671:9)
    at async NextNodeServer.handleCatchallRenderRequest (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:302:37)
    at async NextNodeServer.handleRequestImpl (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:899:17)
    at async invokeRender (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:237:21)
    at async handleRequest (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:428:24)
    at async requestHandlerImpl (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:452:13)
[2025-06-29T10:34:14.866Z] error: undefined
[2025-06-29T10:34:14.867Z] error: TypeError: Invalid URL
    at new URL (node:internal/url:818:25)
    at y (/app/.next/server/pages/api/services/proxy.js:45:14628)
    at async X (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:18441)
    at async z.render (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:19237)
    at async NextNodeServer.runApi (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:671:9)
    at async NextNodeServer.handleCatchallRenderRequest (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:302:37)
    at async NextNodeServer.handleRequestImpl (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:899:17)
    at async invokeRender (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:237:21)
    at async handleRequest (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:428:24)
    at async requestHandlerImpl (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:452:13)
[2025-06-29T10:34:15.149Z] error: undefined
[2025-06-29T10:34:15.151Z] error: TypeError: Invalid URL
    at new URL (node:internal/url:818:25)
    at y (/app/.next/server/pages/api/services/proxy.js:45:14628)
    at async X (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:18441)
    at async z.render (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:19237)
    at async NextNodeServer.runApi (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:671:9)
    at async NextNodeServer.handleCatchallRenderRequest (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:302:37)
    at async NextNodeServer.handleRequestImpl (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:899:17)
    at async invokeRender (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:237:21)
    at async handleRequest (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:428:24)
    at async requestHandlerImpl (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:452:13)
[2025-06-29T10:34:20.165Z] error: undefined
[2025-06-29T10:34:20.167Z] error: TypeError: Invalid URL
    at new URL (node:internal/url:818:25)
    at y (/app/.next/server/pages/api/services/proxy.js:45:14628)
    at async X (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:18441)
    at async z.render (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:19237)
    at async NextNodeServer.runApi (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:671:9)
    at async NextNodeServer.handleCatchallRenderRequest (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:302:37)
    at async NextNodeServer.handleRequestImpl (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:899:17)
    at async invokeRender (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:237:21)
    at async handleRequest (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:428:24)
    at async requestHandlerImpl (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:452:13)
[2025-06-29T10:34:30.182Z] error: undefined
[2025-06-29T10:34:30.184Z] error: TypeError: Invalid URL
    at new URL (node:internal/url:818:25)
    at y (/app/.next/server/pages/api/services/proxy.js:45:14628)
    at async X (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:18441)
    at async z.render (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:19237)
    at async NextNodeServer.runApi (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:671:9)
    at async NextNodeServer.handleCatchallRenderRequest (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:302:37)
    at async NextNodeServer.handleRequestImpl (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:899:17)
    at async invokeRender (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:237:21)
    at async handleRequest (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:428:24)
    at async requestHandlerImpl (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:452:13)
[2025-06-29T10:34:31.138Z] error: undefined
[2025-06-29T10:34:31.139Z] error: TypeError: Invalid URL
    at new URL (node:internal/url:818:25)
    at y (/app/.next/server/pages/api/services/proxy.js:45:14628)
    at async X (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:18441)
    at async z.render (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:19237)
    at async NextNodeServer.runApi (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:671:9)
    at async NextNodeServer.handleCatchallRenderRequest (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:302:37)
    at async NextNodeServer.handleRequestImpl (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:899:17)
    at async invokeRender (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:237:21)
    at async handleRequest (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:428:24)
    at async requestHandlerImpl (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:452:13)
[2025-06-29T10:34:31.282Z] error: undefined
[2025-06-29T10:34:31.284Z] error: TypeError: Invalid URL
    at new URL (node:internal/url:818:25)
    at y (/app/.next/server/pages/api/services/proxy.js:45:14628)
    at async X (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:18441)
    at async z.render (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:19237)
    at async NextNodeServer.runApi (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:671:9)
    at async NextNodeServer.handleCatchallRenderRequest (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:302:37)
    at async NextNodeServer.handleRequestImpl (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:899:17)
    at async invokeRender (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:237:21)
    at async handleRequest (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:428:24)
    at async requestHandlerImpl (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:452:13)
[2025-06-29T10:34:39.045Z] error: undefined
[2025-06-29T10:34:39.047Z] error: TypeError: Invalid URL
    at new URL (node:internal/url:818:25)
    at y (/app/.next/server/pages/api/services/proxy.js:45:14628)
    at async X (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:18441)
    at async z.render (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:19237)
    at async NextNodeServer.runApi (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:671:9)
    at async NextNodeServer.handleCatchallRenderRequest (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:302:37)
    at async NextNodeServer.handleRequestImpl (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:899:17)
    at async invokeRender (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:237:21)
    at async handleRequest (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:428:24)
    at async requestHandlerImpl (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:452:13)
[2025-06-29T10:34:39.203Z] error: undefined
[2025-06-29T10:34:39.204Z] error: TypeError: Invalid URL
    at new URL (node:internal/url:818:25)
    at y (/app/.next/server/pages/api/services/proxy.js:45:14628)
    at async X (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:18441)
    at async z.render (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:19237)
    at async NextNodeServer.runApi (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:671:9)
    at async NextNodeServer.handleCatchallRenderRequest (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:302:37)
    at async NextNodeServer.handleRequestImpl (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:899:17)
    at async invokeRender (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:237:21)
    at async handleRequest (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:428:24)
    at async requestHandlerImpl (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:452:13)
[2025-06-29T10:34:49.832Z] error: undefined
[2025-06-29T10:34:49.834Z] error: TypeError: Invalid URL
    at new URL (node:internal/url:818:25)
    at y (/app/.next/server/pages/api/services/proxy.js:45:14628)
    at async X (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:18441)
    at async z.render (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:19237)
    at async NextNodeServer.runApi (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:671:9)
    at async NextNodeServer.handleCatchallRenderRequest (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:302:37)
    at async NextNodeServer.handleRequestImpl (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:899:17)
    at async invokeRender (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:237:21)
    at async handleRequest (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:428:24)
    at async requestHandlerImpl (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:452:13)
[2025-06-29T10:34:58.731Z] error: undefined
[2025-06-29T10:34:58.733Z] error: TypeError: Invalid URL
    at new URL (node:internal/url:818:25)
    at y (/app/.next/server/pages/api/services/proxy.js:45:14628)
    at async X (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:18441)
    at async z.render (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:19237)
    at async NextNodeServer.runApi (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:671:9)
    at async NextNodeServer.handleCatchallRenderRequest (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:302:37)
    at async NextNodeServer.handleRequestImpl (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:899:17)
    at async invokeRender (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:237:21)
    at async handleRequest (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:428:24)
    at async requestHandlerImpl (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:452:13)
[2025-06-29T10:35:08.855Z] error: undefined
[2025-06-29T10:35:08.857Z] error: TypeError: Invalid URL
    at new URL (node:internal/url:818:25)
    at y (/app/.next/server/pages/api/services/proxy.js:45:14628)
    at async X (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:18441)
    at async z.render (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:19237)
    at async NextNodeServer.runApi (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:671:9)
    at async NextNodeServer.handleCatchallRenderRequest (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:302:37)
    at async NextNodeServer.handleRequestImpl (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:899:17)
    at async invokeRender (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:237:21)
    at async handleRequest (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:428:24)
    at async requestHandlerImpl (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:452:13)
[2025-06-29T10:36:47.861Z] error: undefined
[2025-06-29T10:36:47.862Z] error: TypeError: Invalid URL
    at new URL (node:internal/url:818:25)
    at y (/app/.next/server/pages/api/services/proxy.js:45:14628)
    at async X (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:18441)
    at async z.render (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:19237)
    at async NextNodeServer.runApi (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:671:9)
    at async NextNodeServer.handleCatchallRenderRequest (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:302:37)
    at async NextNodeServer.handleRequestImpl (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:899:17)
    at async invokeRender (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:237:21)
    at async handleRequest (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:428:24)
    at async requestHandlerImpl (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:452:13)
[2025-06-29T10:36:48.073Z] error: undefined
[2025-06-29T10:36:48.074Z] error: TypeError: Invalid URL
    at new URL (node:internal/url:818:25)
    at y (/app/.next/server/pages/api/services/proxy.js:45:14628)
    at async X (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:18441)
    at async z.render (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:19237)
    at async NextNodeServer.runApi (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:671:9)
    at async NextNodeServer.handleCatchallRenderRequest (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:302:37)
    at async NextNodeServer.handleRequestImpl (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:899:17)
    at async invokeRender (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:237:21)
    at async handleRequest (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:428:24)
    at async requestHandlerImpl (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:452:13)
[2025-06-29T10:36:53.101Z] error: undefined
[2025-06-29T10:36:53.103Z] error: TypeError: Invalid URL
    at new URL (node:internal/url:818:25)
    at y (/app/.next/server/pages/api/services/proxy.js:45:14628)
    at async X (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:18441)
    at async z.render (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:19237)
    at async NextNodeServer.runApi (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:671:9)
    at async NextNodeServer.handleCatchallRenderRequest (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:302:37)
    at async NextNodeServer.handleRequestImpl (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:899:17)
    at async invokeRender (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:237:21)
    at async handleRequest (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:428:24)
    at async requestHandlerImpl (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:452:13)
[2025-06-29T10:37:02.768Z] error: undefined
[2025-06-29T10:37:02.770Z] error: TypeError: Invalid URL
    at new URL (node:internal/url:818:25)
    at y (/app/.next/server/pages/api/services/proxy.js:45:14628)
    at async X (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:18441)
    at async z.render (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:19237)
    at async NextNodeServer.runApi (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:671:9)
    at async NextNodeServer.handleCatchallRenderRequest (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:302:37)
    at async NextNodeServer.handleRequestImpl (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:899:17)
    at async invokeRender (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:237:21)
    at async handleRequest (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:428:24)
    at async requestHandlerImpl (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:452:13)
[2025-06-29T10:37:02.943Z] error: undefined
[2025-06-29T10:37:02.944Z] error: TypeError: Invalid URL
    at new URL (node:internal/url:818:25)
    at y (/app/.next/server/pages/api/services/proxy.js:45:14628)
    at async X (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:18441)
    at async z.render (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:19237)
    at async NextNodeServer.runApi (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:671:9)
    at async NextNodeServer.handleCatchallRenderRequest (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:302:37)
    at async NextNodeServer.handleRequestImpl (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:899:17)
    at async invokeRender (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:237:21)
    at async handleRequest (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:428:24)
    at async requestHandlerImpl (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:452:13)
[2025-06-29T10:37:08.826Z] error: undefined
[2025-06-29T10:37:08.828Z] error: TypeError: Invalid URL
    at new URL (node:internal/url:818:25)
    at y (/app/.next/server/pages/api/services/proxy.js:45:14628)
    at async X (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:18441)
    at async z.render (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:19237)
    at async NextNodeServer.runApi (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:671:9)
    at async NextNodeServer.handleCatchallRenderRequest (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:302:37)
    at async NextNodeServer.handleRequestImpl (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:899:17)
    at async invokeRender (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:237:21)
    at async handleRequest (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:428:24)
    at async requestHandlerImpl (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:452:13)
[2025-06-29T10:38:49.230Z] error: undefined
[2025-06-29T10:38:49.231Z] error: TypeError: Invalid URL
    at new URL (node:internal/url:818:25)
    at y (/app/.next/server/pages/api/services/proxy.js:45:14628)
    at async X (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:18441)
    at async z.render (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:19237)
    at async NextNodeServer.runApi (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:671:9)
    at async NextNodeServer.handleCatchallRenderRequest (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:302:37)
    at async NextNodeServer.handleRequestImpl (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:899:17)
    at async invokeRender (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:237:21)
    at async handleRequest (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:428:24)
    at async requestHandlerImpl (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:452:13)
[2025-06-29T10:38:54.814Z] error: undefined
[2025-06-29T10:38:54.816Z] error: TypeError: Invalid URL
    at new URL (node:internal/url:818:25)
    at y (/app/.next/server/pages/api/services/proxy.js:45:14628)
    at async X (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:18441)
    at async z.render (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:19237)
    at async NextNodeServer.runApi (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:671:9)
    at async NextNodeServer.handleCatchallRenderRequest (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:302:37)
    at async NextNodeServer.handleRequestImpl (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:899:17)
    at async invokeRender (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:237:21)
    at async handleRequest (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:428:24)
    at async requestHandlerImpl (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:452:13)
[2025-06-29T10:42:18.626Z] error: <httpProxy> Error calling http://192.168.0.133:22070/status...
[2025-06-29T10:42:18.627Z] error: <httpProxy> [
  500,
  Error: connect ECONNREFUSED 192.168.0.133:22070
      at <unknown> (Error: connect ECONNREFUSED 192.168.0.133:22070) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '192.168.0.133',
    port: 22070
  }
]
[2025-06-29T10:42:18.781Z] error: <httpProxy> Error calling http://192.168.0.133:22070/status...
[2025-06-29T10:42:18.782Z] error: <httpProxy> [
  500,
  Error: connect ECONNREFUSED 192.168.0.133:22070
      at <unknown> (Error: connect ECONNREFUSED 192.168.0.133:22070) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '192.168.0.133',
    port: 22070
  }
]
[2025-06-29T10:42:33.769Z] error: <httpProxy> Error calling http://192.168.0.133:8343/status...
[2025-06-29T10:42:33.770Z] error: <httpProxy> [
  500,
  Error: connect ECONNREFUSED 192.168.0.133:8343
      at <unknown> (Error: connect ECONNREFUSED 192.168.0.133:8343) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '192.168.0.133',
    port: 8343
  }
]
[2025-06-29T10:42:33.948Z] error: <httpProxy> Error calling http://192.168.0.133:8343/status...
[2025-06-29T10:42:33.949Z] error: <httpProxy> [
  500,
  Error: connect ECONNREFUSED 192.168.0.133:8343
      at <unknown> (Error: connect ECONNREFUSED 192.168.0.133:8343) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '192.168.0.133',
    port: 8343
  }
]
[2025-06-29T10:42:45.678Z] error: <httpProxy> Error calling http://192.168.0.133:8343/status...
[2025-06-29T10:42:45.679Z] error: <httpProxy> [
  500,
  Error: connect ECONNREFUSED 192.168.0.133:8343
      at <unknown> (Error: connect ECONNREFUSED 192.168.0.133:8343) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '192.168.0.133',
    port: 8343
  }
]
[2025-06-29T10:44:21.336Z] error: <httpProxy> Error calling http://192.168.0.133:8343/...
[2025-06-29T10:44:21.337Z] error: <httpProxy> [
  500,
  Error: connect ECONNREFUSED 192.168.0.133:8343
      at <unknown> (Error: connect ECONNREFUSED 192.168.0.133:8343) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '192.168.0.133',
    port: 8343
  }
]
[2025-06-29T10:44:21.553Z] error: <httpProxy> Error calling http://192.168.0.133:8343/...
[2025-06-29T10:44:21.554Z] error: <httpProxy> [
  500,
  Error: connect ECONNREFUSED 192.168.0.133:8343
      at <unknown> (Error: connect ECONNREFUSED 192.168.0.133:8343) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '192.168.0.133',
    port: 8343
  }
]
[2025-06-30T02:32:35.656Z] error: <piholeProxyHandler> Failed to login to Pi-Hole API, status: 401
[2025-07-02T12:52:16.569Z] error: <httpProxy> Error calling https://nc.papatenko.org/ocs/v2.php/apps/serverinfo/api/v1/info...
[2025-07-02T12:52:16.581Z] error: <httpProxy> [
  500,
  Error: connect ETIMEDOUT 76.231.153.102:443
      at <unknown> (Error: connect ETIMEDOUT 76.231.153.102:443) {
    errno: -110,
    code: 'ETIMEDOUT',
    syscall: 'connect',
    address: '76.231.153.102',
    port: 443
  }
]
[2025-07-02T12:52:16.583Z] error: <credentialedProxyHandler> HTTP Error 500 calling https://nc.papatenko.org/ocs/v2.php/apps/serverinfo/api/v1/info?format=json
[2025-07-02T12:54:07.158Z] error: <httpProxy> Error calling https://nc.papatenko.org/ocs/v2.php/apps/serverinfo/api/v1/info...
[2025-07-02T12:54:07.161Z] error: <httpProxy> [
  500,
  Error: connect ETIMEDOUT 76.231.153.102:443
      at <unknown> (Error: connect ETIMEDOUT 76.231.153.102:443) {
    errno: -110,
    code: 'ETIMEDOUT',
    syscall: 'connect',
    address: '76.231.153.102',
    port: 443
  }
]
[2025-07-02T12:54:07.161Z] error: <credentialedProxyHandler> HTTP Error 500 calling https://nc.papatenko.org/ocs/v2.php/apps/serverinfo/api/v1/info?format=json
[2025-07-02T12:55:57.750Z] error: <httpProxy> Error calling https://nc.papatenko.org/ocs/v2.php/apps/serverinfo/api/v1/info...
[2025-07-02T12:55:57.752Z] error: <httpProxy> [
  500,
  Error: connect ETIMEDOUT 76.231.153.102:443
      at <unknown> (Error: connect ETIMEDOUT 76.231.153.102:443) {
    errno: -110,
    code: 'ETIMEDOUT',
    syscall: 'connect',
    address: '76.231.153.102',
    port: 443
  }
]
[2025-07-02T12:55:57.752Z] error: <credentialedProxyHandler> HTTP Error 500 calling https://nc.papatenko.org/ocs/v2.php/apps/serverinfo/api/v1/info?format=json
[2025-07-02T12:56:32.566Z] error: <httpProxy> Error calling https://nc.papatenko.org/ocs/v2.php/apps/serverinfo/api/v1/info...
[2025-07-02T12:56:32.568Z] error: <httpProxy> [
  500,
  Error: connect ETIMEDOUT 76.231.153.102:443
      at <unknown> (Error: connect ETIMEDOUT 76.231.153.102:443) {
    errno: -110,
    code: 'ETIMEDOUT',
    syscall: 'connect',
    address: '76.231.153.102',
    port: 443
  }
]
[2025-07-02T12:56:32.568Z] error: <credentialedProxyHandler> HTTP Error 500 calling https://nc.papatenko.org/ocs/v2.php/apps/serverinfo/api/v1/info?format=json
[2025-07-02T12:56:36.662Z] error: <httpProxy> Error calling https://nc.papatenko.org/ocs/v2.php/apps/serverinfo/api/v1/info...
[2025-07-02T12:56:36.665Z] error: <httpProxy> [
  500,
  Error: connect ETIMEDOUT 76.231.153.102:443
      at <unknown> (Error: connect ETIMEDOUT 76.231.153.102:443) {
    errno: -110,
    code: 'ETIMEDOUT',
    syscall: 'connect',
    address: '76.231.153.102',
    port: 443
  }
]
[2025-07-02T12:56:36.665Z] error: <credentialedProxyHandler> HTTP Error 500 calling https://nc.papatenko.org/ocs/v2.php/apps/serverinfo/api/v1/info?format=json
[2025-07-02T13:08:29.366Z] error: <httpProxy> Error calling https://nc.papatenko.org/ocs/v2.php/apps/serverinfo/api/v1/info...
[2025-07-02T13:08:29.368Z] error: <httpProxy> [
  500,
  Error: connect ETIMEDOUT 76.231.153.102:443
      at <unknown> (Error: connect ETIMEDOUT 76.231.153.102:443) {
    errno: -110,
    code: 'ETIMEDOUT',
    syscall: 'connect',
    address: '76.231.153.102',
    port: 443
  }
]
[2025-07-02T13:08:29.368Z] error: <credentialedProxyHandler> HTTP Error 500 calling https://nc.papatenko.org/ocs/v2.php/apps/serverinfo/api/v1/info?format=json
[2025-07-02T13:08:29.369Z] error: <httpProxy> Error calling https://nc.papatenko.org/ocs/v2.php/apps/serverinfo/api/v1/info...
[2025-07-02T13:08:29.370Z] error: <httpProxy> [
  500,
  Error: connect ETIMEDOUT 76.231.153.102:443
      at <unknown> (Error: connect ETIMEDOUT 76.231.153.102:443) {
    errno: -110,
    code: 'ETIMEDOUT',
    syscall: 'connect',
    address: '76.231.153.102',
    port: 443
  }
]
[2025-07-02T13:08:29.370Z] error: <credentialedProxyHandler> HTTP Error 500 calling https://nc.papatenko.org/ocs/v2.php/apps/serverinfo/api/v1/info?format=json
[2025-07-03T00:13:18.263Z] error: <httpProxy> Error calling https://nc.papatenko.org/ocs/v2.php/apps/serverinfo/api/v1/info...
[2025-07-03T00:13:18.264Z] error: <httpProxy> [
  500,
  Error: connect ETIMEDOUT 76.231.153.102:443
      at <unknown> (Error: connect ETIMEDOUT 76.231.153.102:443) {
    errno: -110,
    code: 'ETIMEDOUT',
    syscall: 'connect',
    address: '76.231.153.102',
    port: 443
  }
]
[2025-07-03T00:13:18.264Z] error: <credentialedProxyHandler> HTTP Error 500 calling https://nc.papatenko.org/ocs/v2.php/apps/serverinfo/api/v1/info?format=json
[2025-07-03T00:13:18.265Z] error: <httpProxy> Error calling https://nc.papatenko.org/ocs/v2.php/apps/serverinfo/api/v1/info...
[2025-07-03T00:13:18.265Z] error: <httpProxy> [
  500,
  Error: connect ETIMEDOUT 76.231.153.102:443
      at <unknown> (Error: connect ETIMEDOUT 76.231.153.102:443) {
    errno: -110,
    code: 'ETIMEDOUT',
    syscall: 'connect',
    address: '76.231.153.102',
    port: 443
  }
]
[2025-07-03T00:13:18.265Z] error: <credentialedProxyHandler> HTTP Error 500 calling https://nc.papatenko.org/ocs/v2.php/apps/serverinfo/api/v1/info?format=json
[2025-07-04T17:27:15.154Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://nc.papatenko.org/ocs/v2.php/apps/serverinfo/api/v1/info?format=json
[2025-07-04T17:32:53.080Z] error: <servicesProxy> YAMLException: bad indentation of a mapping entry (27:17)

 24 |     - Syncthing:
 25 |         icon: syncthing
 26 |         href: http://192.168.0.133:8384
 27 |           widget:
----------------------^
 28 |             type: strelaysrv
 29 |             url: http://192.168.0.133:8384
    at generateError (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:1273:10)
    at throwError (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:1277:9)
    at readBlockMapping (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2272:7)
    at composeNode (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2531:12)
    at readBlockMapping (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2254:11)
    at composeNode (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2531:12)
    at readBlockSequence (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2098:5)
    at composeNode (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2530:12)
    at readBlockMapping (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2254:11)
    at composeNode (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2531:12)
[2025-07-04T17:32:53.084Z] error: <servicesProxy> YAMLException: bad indentation of a mapping entry (27:17)

 24 |     - Syncthing:
 25 |         icon: syncthing
 26 |         href: http://192.168.0.133:8384
 27 |           widget:
----------------------^
 28 |             type: strelaysrv
 29 |             url: http://192.168.0.133:8384
    at generateError (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:1273:10)
    at throwError (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:1277:9)
    at readBlockMapping (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2272:7)
    at composeNode (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2531:12)
    at readBlockMapping (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2254:11)
    at composeNode (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2531:12)
    at readBlockSequence (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2098:5)
    at composeNode (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2530:12)
    at readBlockMapping (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2254:11)
    at composeNode (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2531:12)
[2025-07-04T17:32:53.085Z] error: <servicesProxy> YAMLException: bad indentation of a mapping entry (27:17)

 24 |     - Syncthing:
 25 |         icon: syncthing
 26 |         href: http://192.168.0.133:8384
 27 |           widget:
----------------------^
 28 |             type: strelaysrv
 29 |             url: http://192.168.0.133:8384
    at generateError (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:1273:10)
    at throwError (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:1277:9)
    at readBlockMapping (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2272:7)
    at composeNode (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2531:12)
    at readBlockMapping (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2254:11)
    at composeNode (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2531:12)
    at readBlockSequence (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2098:5)
    at composeNode (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2530:12)
    at readBlockMapping (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2254:11)
    at composeNode (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2531:12)
[2025-07-04T17:32:53.106Z] error: Failed to load services.yaml, please check for errors
[2025-07-04T17:32:53.107Z] error: YAMLException: bad indentation of a mapping entry (27:17)

 24 |     - Syncthing:
 25 |         icon: syncthing
 26 |         href: http://192.168.0.133:8384
 27 |           widget:
----------------------^
 28 |             type: strelaysrv
 29 |             url: http://192.168.0.133:8384
[2025-07-04T17:32:53.133Z] error: Failed to load services.yaml, please check for errors
[2025-07-04T17:32:53.133Z] error: YAMLException: bad indentation of a mapping entry (27:17)

 24 |     - Syncthing:
 25 |         icon: syncthing
 26 |         href: http://192.168.0.133:8384
 27 |           widget:
----------------------^
 28 |             type: strelaysrv
 29 |             url: http://192.168.0.133:8384
[2025-07-04T17:32:53.320Z] error: Failed to load services.yaml, please check for errors
[2025-07-04T17:32:53.320Z] error: YAMLException: bad indentation of a mapping entry (27:17)

 24 |     - Syncthing:
 25 |         icon: syncthing
 26 |         href: http://192.168.0.133:8384
 27 |           widget:
----------------------^
 28 |             type: strelaysrv
 29 |             url: http://192.168.0.133:8384
[2025-07-04T17:36:56.887Z] error: <httpProxy> Error calling https://nc.papatenko.org/ocs/v2.php/apps/serverinfo/api/v1/info...
[2025-07-04T17:36:56.894Z] error: <httpProxy> [
  500,
  Error: connect ETIMEDOUT 76.231.153.102:443
      at <unknown> (Error: connect ETIMEDOUT 76.231.153.102:443) {
    errno: -110,
    code: 'ETIMEDOUT',
    syscall: 'connect',
    address: '76.231.153.102',
    port: 443
  }
]
[2025-07-04T17:36:56.895Z] error: <credentialedProxyHandler> HTTP Error 500 calling https://nc.papatenko.org/ocs/v2.php/apps/serverinfo/api/v1/info?format=json
[2025-07-05T19:59:50.839Z] error: <httpProxy> Error calling https://nc.papatenko.org/ocs/v2.php/apps/serverinfo/api/v1/info...
[2025-07-05T19:59:50.844Z] error: <httpProxy> [
  500,
  Error: connect ETIMEDOUT 76.231.153.102:443
      at <unknown> (Error: connect ETIMEDOUT 76.231.153.102:443) {
    errno: -110,
    code: 'ETIMEDOUT',
    syscall: 'connect',
    address: '76.231.153.102',
    port: 443
  }
]
[2025-07-05T19:59:50.845Z] error: <credentialedProxyHandler> HTTP Error 500 calling https://nc.papatenko.org/ocs/v2.php/apps/serverinfo/api/v1/info?format=json
[2025-07-05T22:02:19.062Z] error: <httpProxy> Error calling https://nc.papatenko.org/ocs/v2.php/apps/serverinfo/api/v1/info...
[2025-07-05T22:02:19.065Z] error: <httpProxy> [
  500,
  Error: connect ETIMEDOUT 76.231.153.102:443
      at <unknown> (Error: connect ETIMEDOUT 76.231.153.102:443) {
    errno: -110,
    code: 'ETIMEDOUT',
    syscall: 'connect',
    address: '76.231.153.102',
    port: 443
  }
]
[2025-07-05T22:02:19.066Z] error: <credentialedProxyHandler> HTTP Error 500 calling https://nc.papatenko.org/ocs/v2.php/apps/serverinfo/api/v1/info?format=json
[2025-07-05T22:09:06.614Z] error: <httpProxy> Error calling https://nc.papatenko.org/ocs/v2.php/apps/serverinfo/api/v1/info...
[2025-07-05T22:09:06.615Z] error: <httpProxy> [
  500,
  Error: connect ETIMEDOUT 76.231.153.102:443
      at <unknown> (Error: connect ETIMEDOUT 76.231.153.102:443) {
    errno: -110,
    code: 'ETIMEDOUT',
    syscall: 'connect',
    address: '76.231.153.102',
    port: 443
  }
]
[2025-07-05T22:09:06.616Z] error: <credentialedProxyHandler> HTTP Error 500 calling https://nc.papatenko.org/ocs/v2.php/apps/serverinfo/api/v1/info?format=json
[2025-07-05T22:19:06.678Z] error: <httpProxy> Error calling https://nc.papatenko.org/ocs/v2.php/apps/serverinfo/api/v1/info...
[2025-07-05T22:19:06.680Z] error: <httpProxy> [
  500,
  Error: connect ETIMEDOUT 76.231.153.102:443
      at <unknown> (Error: connect ETIMEDOUT 76.231.153.102:443) {
    errno: -110,
    code: 'ETIMEDOUT',
    syscall: 'connect',
    address: '76.231.153.102',
    port: 443
  }
]
[2025-07-05T22:19:06.680Z] error: <credentialedProxyHandler> HTTP Error 500 calling https://nc.papatenko.org/ocs/v2.php/apps/serverinfo/api/v1/info?format=json
[2025-07-05T22:20:32.694Z] error: <httpProxy> Error calling https://nc.papatenko.org/ocs/v2.php/apps/serverinfo/api/v1/info...
[2025-07-05T22:20:32.697Z] error: <httpProxy> [
  500,
  Error: connect ETIMEDOUT 76.231.153.102:443
      at <unknown> (Error: connect ETIMEDOUT 76.231.153.102:443) {
    errno: -110,
    code: 'ETIMEDOUT',
    syscall: 'connect',
    address: '76.231.153.102',
    port: 443
  }
]
[2025-07-05T22:20:32.697Z] error: <credentialedProxyHandler> HTTP Error 500 calling https://nc.papatenko.org/ocs/v2.php/apps/serverinfo/api/v1/info?format=json
[2025-07-05T22:27:20.246Z] error: <httpProxy> Error calling https://nc.papatenko.org/ocs/v2.php/apps/serverinfo/api/v1/info...
[2025-07-05T22:27:20.247Z] error: <httpProxy> [
  500,
  Error: connect ETIMEDOUT 76.231.153.102:443
      at <unknown> (Error: connect ETIMEDOUT 76.231.153.102:443) {
    errno: -110,
    code: 'ETIMEDOUT',
    syscall: 'connect',
    address: '76.231.153.102',
    port: 443
  }
]
[2025-07-05T22:27:20.247Z] error: <credentialedProxyHandler> HTTP Error 500 calling https://nc.papatenko.org/ocs/v2.php/apps/serverinfo/api/v1/info?format=json
[2025-07-05T22:27:30.486Z] error: <httpProxy> Error calling https://nc.papatenko.org/ocs/v2.php/apps/serverinfo/api/v1/info...
[2025-07-05T22:27:30.487Z] error: <httpProxy> [
  500,
  Error: connect ETIMEDOUT 76.231.153.102:443
      at <unknown> (Error: connect ETIMEDOUT 76.231.153.102:443) {
    errno: -110,
    code: 'ETIMEDOUT',
    syscall: 'connect',
    address: '76.231.153.102',
    port: 443
  }
]
[2025-07-05T22:27:30.487Z] error: <credentialedProxyHandler> HTTP Error 500 calling https://nc.papatenko.org/ocs/v2.php/apps/serverinfo/api/v1/info?format=json
[2025-07-05T22:36:25.014Z] error: <httpProxy> Error calling https://nc.papatenko.org/ocs/v2.php/apps/serverinfo/api/v1/info...
[2025-07-05T22:36:25.015Z] error: <httpProxy> [
  500,
  Error: connect ETIMEDOUT 76.231.153.102:443
      at <unknown> (Error: connect ETIMEDOUT 76.231.153.102:443) {
    errno: -110,
    code: 'ETIMEDOUT',
    syscall: 'connect',
    address: '76.231.153.102',
    port: 443
  }
]
[2025-07-05T22:36:25.015Z] error: <credentialedProxyHandler> HTTP Error 500 calling https://nc.papatenko.org/ocs/v2.php/apps/serverinfo/api/v1/info?format=json
[2025-07-08T23:17:35.927Z] error: <httpProxy> Error calling https://nc.papatenko.org/ocs/v2.php/apps/serverinfo/api/v1/info...
[2025-07-08T23:17:35.929Z] error: <httpProxy> [
  500,
  Error: connect ETIMEDOUT 76.231.153.102:443
      at <unknown> (Error: connect ETIMEDOUT 76.231.153.102:443) {
    errno: -110,
    code: 'ETIMEDOUT',
    syscall: 'connect',
    address: '76.231.153.102',
    port: 443
  }
]
[2025-07-08T23:17:35.929Z] error: <credentialedProxyHandler> HTTP Error 500 calling https://nc.papatenko.org/ocs/v2.php/apps/serverinfo/api/v1/info?format=json
[2025-07-08T23:46:03.946Z] error: <servicesProxy> YAMLException: bad indentation of a mapping entry (25:15)

 22 |   - WGEasy:
 23 |       icon: wg-easy
 24 |       href: https://wg.papatenko.org/
 25 |         widget:
--------------------^
 26 |           type: wgeasy
 27 |           url: https://wg.papatenko.org/
    at generateError (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:1273:10)
    at throwError (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:1277:9)
    at readBlockMapping (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2272:7)
    at composeNode (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2531:12)
    at readBlockMapping (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2254:11)
    at composeNode (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2531:12)
    at readBlockSequence (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2098:5)
    at composeNode (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2562:45)
    at readBlockMapping (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2254:11)
    at composeNode (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2531:12)
[2025-07-08T23:46:03.948Z] error: <servicesProxy> YAMLException: bad indentation of a mapping entry (25:15)

 22 |   - WGEasy:
 23 |       icon: wg-easy
 24 |       href: https://wg.papatenko.org/
 25 |         widget:
--------------------^
 26 |           type: wgeasy
 27 |           url: https://wg.papatenko.org/
    at generateError (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:1273:10)
    at throwError (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:1277:9)
    at readBlockMapping (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2272:7)
    at composeNode (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2531:12)
    at readBlockMapping (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2254:11)
    at composeNode (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2531:12)
    at readBlockSequence (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2098:5)
    at composeNode (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2562:45)
    at readBlockMapping (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2254:11)
    at composeNode (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2531:12)
[2025-07-08T23:46:03.966Z] error: Failed to load services.yaml, please check for errors
[2025-07-08T23:46:03.966Z] error: YAMLException: bad indentation of a mapping entry (25:15)

 22 |   - WGEasy:
 23 |       icon: wg-easy
 24 |       href: https://wg.papatenko.org/
 25 |         widget:
--------------------^
 26 |           type: wgeasy
 27 |           url: https://wg.papatenko.org/
[2025-07-08T23:46:04.008Z] error: Failed to load services.yaml, please check for errors
[2025-07-08T23:46:04.008Z] error: YAMLException: bad indentation of a mapping entry (25:15)

 22 |   - WGEasy:
 23 |       icon: wg-easy
 24 |       href: https://wg.papatenko.org/
 25 |         widget:
--------------------^
 26 |           type: wgeasy
 27 |           url: https://wg.papatenko.org/
[2025-07-08T23:46:04.253Z] error: Failed to load services.yaml, please check for errors
[2025-07-08T23:46:04.253Z] error: YAMLException: bad indentation of a mapping entry (25:15)

 22 |   - WGEasy:
 23 |       icon: wg-easy
 24 |       href: https://wg.papatenko.org/
 25 |         widget:
--------------------^
 26 |           type: wgeasy
 27 |           url: https://wg.papatenko.org/
[2025-07-08T23:46:16.246Z] error: <httpProxy> Error calling https://nc.papatenko.org/ocs/v2.php/apps/serverinfo/api/v1/info...
[2025-07-08T23:46:16.247Z] error: <httpProxy> [
  500,
  Error: connect ETIMEDOUT 76.231.153.102:443
      at <unknown> (Error: connect ETIMEDOUT 76.231.153.102:443) {
    errno: -110,
    code: 'ETIMEDOUT',
    syscall: 'connect',
    address: '76.231.153.102',
    port: 443
  }
]
[2025-07-08T23:46:16.247Z] error: <credentialedProxyHandler> HTTP Error 500 calling https://nc.papatenko.org/ocs/v2.php/apps/serverinfo/api/v1/info?format=json
[2025-07-08T23:50:44.536Z] error: <httpProxy> Error calling https://nc.papatenko.org/ocs/v2.php/apps/serverinfo/api/v1/info...
[2025-07-08T23:50:44.544Z] error: <httpProxy> [
  500,
  Error: connect ETIMEDOUT 76.231.153.102:443
      at <unknown> (Error: connect ETIMEDOUT 76.231.153.102:443) {
    errno: -110,
    code: 'ETIMEDOUT',
    syscall: 'connect',
    address: '76.231.153.102',
    port: 443
  }
]
[2025-07-08T23:50:44.545Z] error: <credentialedProxyHandler> HTTP Error 500 calling https://nc.papatenko.org/ocs/v2.php/apps/serverinfo/api/v1/info?format=json
[2025-07-08T23:50:44.546Z] error: <httpProxy> Error calling https://wg.papatenko.org/api/client...
[2025-07-08T23:50:44.549Z] error: <httpProxy> [
  500,
  Error: connect ETIMEDOUT 76.231.153.102:443
      at <unknown> (Error: connect ETIMEDOUT 76.231.153.102:443) {
    errno: -110,
    code: 'ETIMEDOUT',
    syscall: 'connect',
    address: '76.231.153.102',
    port: 443
  }
]
[2025-07-08T23:50:44.549Z] error: <credentialedProxyHandler> HTTP Error 500 calling https://wg.papatenko.org/api/client
[2025-07-08T23:50:46.582Z] error: <httpProxy> Error calling https://nc.papatenko.org/ocs/v2.php/apps/serverinfo/api/v1/info...
[2025-07-08T23:50:46.584Z] error: <httpProxy> [
  500,
  Error: connect ETIMEDOUT 76.231.153.102:443
      at <unknown> (Error: connect ETIMEDOUT 76.231.153.102:443) {
    errno: -110,
    code: 'ETIMEDOUT',
    syscall: 'connect',
    address: '76.231.153.102',
    port: 443
  }
]
[2025-07-08T23:50:46.585Z] error: <credentialedProxyHandler> HTTP Error 500 calling https://nc.papatenko.org/ocs/v2.php/apps/serverinfo/api/v1/info?format=json
[2025-07-08T23:50:46.586Z] error: <httpProxy> Error calling https://wg.papatenko.org/api/client...
[2025-07-08T23:50:46.587Z] error: <httpProxy> [
  500,
  Error: connect ETIMEDOUT 76.231.153.102:443
      at <unknown> (Error: connect ETIMEDOUT 76.231.153.102:443) {
    errno: -110,
    code: 'ETIMEDOUT',
    syscall: 'connect',
    address: '76.231.153.102',
    port: 443
  }
]
[2025-07-08T23:50:46.587Z] error: <credentialedProxyHandler> HTTP Error 500 calling https://wg.papatenko.org/api/client
[2025-07-08T23:51:52.119Z] error: <httpProxy> Error calling https://nc.papatenko.org/ocs/v2.php/apps/serverinfo/api/v1/info...
[2025-07-08T23:51:52.121Z] error: <httpProxy> [
  500,
  Error: connect ETIMEDOUT 76.231.153.102:443
      at <unknown> (Error: connect ETIMEDOUT 76.231.153.102:443) {
    errno: -110,
    code: 'ETIMEDOUT',
    syscall: 'connect',
    address: '76.231.153.102',
    port: 443
  }
]
[2025-07-08T23:51:52.121Z] error: <credentialedProxyHandler> HTTP Error 500 calling https://nc.papatenko.org/ocs/v2.php/apps/serverinfo/api/v1/info?format=json
[2025-07-09T00:04:59.904Z] error: <httpProxy> Error calling http://192.168.0.133:51821/api/client...
[2025-07-09T00:04:59.906Z] error: <httpProxy> [ 500, [Error: socket hang up] { code: 'ECONNRESET' } ]
[2025-07-09T00:04:59.906Z] error: <credentialedProxyHandler> HTTP Error 500 calling http://192.168.0.133:51821/api/client
[2025-08-13T16:44:23.860Z] error: <httpProxy> Error calling http://192.168.0.133:11000/ocs/v2.php/apps/serverinfo/api/v1/info...
[2025-08-13T16:44:23.879Z] error: <httpProxy> [
  500,
  Error: connect ECONNREFUSED 192.168.0.133:11000
      at <unknown> (Error: connect ECONNREFUSED 192.168.0.133:11000) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '192.168.0.133',
    port: 11000
  }
]
[2025-08-13T16:44:23.880Z] error: <credentialedProxyHandler> HTTP Error 500 calling http://192.168.0.133:11000/ocs/v2.php/apps/serverinfo/api/v1/info?format=json
[2025-08-24T04:24:00.167Z] error: <httpProxy> Error calling https://$:8443/api/auth...
[2025-08-24T04:24:00.175Z] error: undefined
[2025-08-24T04:24:00.173Z] error: <httpProxy> [
  500,
  [Error: getaddrinfo EAI_AGAIN $] {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: '$'
  }
]
[2025-08-24T04:24:00.181Z] error: SyntaxError: "[object Object]" is not valid JSON
    at JSON.parse (<anonymous>)
    at c (/app/.next/server/pages/api/services/proxy.js:45:67782)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async y (/app/.next/server/pages/api/services/proxy.js:45:68527)
    at async X (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:18441)
    at async z.render (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:19237)
    at async NextNodeServer.runApi (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:671:9)
    at async NextNodeServer.handleCatchallRenderRequest (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:302:37)
    at async NextNodeServer.handleRequestImpl (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:899:17)
    at async invokeRender (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:237:21)
[2025-08-24T04:24:00.990Z] error: <httpProxy> Error calling https://$:8443/api/auth...
[2025-08-24T04:24:00.993Z] error: undefined
[2025-08-24T04:24:00.993Z] error: <httpProxy> [
  500,
  [Error: getaddrinfo EAI_AGAIN $] {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: '$'
  }
]
[2025-08-24T04:24:00.996Z] error: SyntaxError: "[object Object]" is not valid JSON
    at JSON.parse (<anonymous>)
    at c (/app/.next/server/pages/api/services/proxy.js:45:67782)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async y (/app/.next/server/pages/api/services/proxy.js:45:68527)
    at async X (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:18441)
    at async z.render (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:19237)
    at async NextNodeServer.runApi (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:671:9)
    at async NextNodeServer.handleCatchallRenderRequest (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:302:37)
    at async NextNodeServer.handleRequestImpl (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:899:17)
    at async invokeRender (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:237:21)
[2025-08-24T04:24:08.285Z] error: <httpProxy> Error calling https://$:8443/api/auth...
[2025-08-24T04:24:08.288Z] error: undefined
[2025-08-24T04:24:08.287Z] error: <httpProxy> [
  500,
  [Error: getaddrinfo EAI_AGAIN $] {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: '$'
  }
]
[2025-08-24T04:24:08.289Z] error: SyntaxError: "[object Object]" is not valid JSON
    at JSON.parse (<anonymous>)
    at c (/app/.next/server/pages/api/services/proxy.js:45:67782)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async y (/app/.next/server/pages/api/services/proxy.js:45:68527)
    at async X (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:18441)
    at async z.render (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:19237)
    at async NextNodeServer.runApi (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:671:9)
    at async NextNodeServer.handleCatchallRenderRequest (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:302:37)
    at async NextNodeServer.handleRequestImpl (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:899:17)
    at async invokeRender (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:237:21)
[2025-08-24T04:25:04.467Z] error: <httpProxy> Error calling https://$:8443/api/auth...
[2025-08-24T04:25:04.468Z] error: undefined
[2025-08-24T04:25:04.468Z] error: <httpProxy> [
  500,
  [Error: getaddrinfo EAI_AGAIN $] {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: '$'
  }
]
[2025-08-24T04:25:04.470Z] error: SyntaxError: "[object Object]" is not valid JSON
    at JSON.parse (<anonymous>)
    at c (/app/.next/server/pages/api/services/proxy.js:45:67782)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async y (/app/.next/server/pages/api/services/proxy.js:45:68527)
    at async X (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:18441)
    at async z.render (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:19237)
    at async NextNodeServer.runApi (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:671:9)
    at async NextNodeServer.handleCatchallRenderRequest (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:302:37)
    at async NextNodeServer.handleRequestImpl (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:899:17)
    at async invokeRender (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:237:21)
[2025-08-24T04:25:05.179Z] error: <httpProxy> Error calling https://$:8443/api/auth...
[2025-08-24T04:25:05.181Z] error: undefined
[2025-08-24T04:25:05.180Z] error: <httpProxy> [
  500,
  [Error: getaddrinfo EAI_AGAIN $] {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: '$'
  }
]
[2025-08-24T04:25:05.182Z] error: SyntaxError: "[object Object]" is not valid JSON
    at JSON.parse (<anonymous>)
    at c (/app/.next/server/pages/api/services/proxy.js:45:67782)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async y (/app/.next/server/pages/api/services/proxy.js:45:68527)
    at async X (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:18441)
    at async z.render (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:19237)
    at async NextNodeServer.runApi (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:671:9)
    at async NextNodeServer.handleCatchallRenderRequest (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:302:37)
    at async NextNodeServer.handleRequestImpl (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:899:17)
    at async invokeRender (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:237:21)
[2025-08-24T04:25:12.238Z] error: <httpProxy> Error calling https://$:8443/api/auth...
[2025-08-24T04:25:12.239Z] error: undefined
[2025-08-24T04:25:12.239Z] error: <httpProxy> [
  500,
  [Error: getaddrinfo EAI_AGAIN $] {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: '$'
  }
]
[2025-08-24T04:25:12.240Z] error: SyntaxError: "[object Object]" is not valid JSON
    at JSON.parse (<anonymous>)
    at c (/app/.next/server/pages/api/services/proxy.js:45:67782)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async y (/app/.next/server/pages/api/services/proxy.js:45:68527)
    at async X (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:18441)
    at async z.render (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:19237)
    at async NextNodeServer.runApi (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:671:9)
    at async NextNodeServer.handleCatchallRenderRequest (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:302:37)
    at async NextNodeServer.handleRequestImpl (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:899:17)
    at async invokeRender (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:237:21)
[2025-08-24T04:25:17.488Z] error: <httpProxy> Error calling https://$:8443/api/auth...
[2025-08-24T04:25:17.489Z] error: undefined
[2025-08-24T04:25:17.488Z] error: <httpProxy> [
  500,
  [Error: getaddrinfo EAI_AGAIN $] {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: '$'
  }
]
[2025-08-24T04:25:17.490Z] error: SyntaxError: "[object Object]" is not valid JSON
    at JSON.parse (<anonymous>)
    at c (/app/.next/server/pages/api/services/proxy.js:45:67782)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async y (/app/.next/server/pages/api/services/proxy.js:45:68527)
    at async X (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:18441)
    at async z.render (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:19237)
    at async NextNodeServer.runApi (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:671:9)
    at async NextNodeServer.handleCatchallRenderRequest (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:302:37)
    at async NextNodeServer.handleRequestImpl (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:899:17)
    at async invokeRender (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:237:21)
[2025-08-24T04:25:22.604Z] error: <httpProxy> Error calling https://$:8443/api/auth...
[2025-08-24T04:25:22.605Z] error: undefined
[2025-08-24T04:25:22.605Z] error: <httpProxy> [
  500,
  [Error: getaddrinfo EAI_AGAIN $] {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: '$'
  }
]
[2025-08-24T04:25:22.606Z] error: SyntaxError: "[object Object]" is not valid JSON
    at JSON.parse (<anonymous>)
    at c (/app/.next/server/pages/api/services/proxy.js:45:67782)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async y (/app/.next/server/pages/api/services/proxy.js:45:68527)
    at async X (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:18441)
    at async z.render (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:19237)
    at async NextNodeServer.runApi (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:671:9)
    at async NextNodeServer.handleCatchallRenderRequest (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:302:37)
    at async NextNodeServer.handleRequestImpl (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:899:17)
    at async invokeRender (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:237:21)
[2025-08-24T04:25:38.117Z] error: <httpProxy> Error calling https://$:8443/api/auth...
[2025-08-24T04:25:38.118Z] error: undefined
[2025-08-24T04:25:38.118Z] error: <httpProxy> [
  500,
  [Error: getaddrinfo EAI_AGAIN $] {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: '$'
  }
]
[2025-08-24T04:25:38.120Z] error: SyntaxError: "[object Object]" is not valid JSON
    at JSON.parse (<anonymous>)
    at c (/app/.next/server/pages/api/services/proxy.js:45:67782)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async y (/app/.next/server/pages/api/services/proxy.js:45:68527)
    at async X (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:18441)
    at async z.render (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:19237)
    at async NextNodeServer.runApi (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:671:9)
    at async NextNodeServer.handleCatchallRenderRequest (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:302:37)
    at async NextNodeServer.handleRequestImpl (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:899:17)
    at async invokeRender (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:237:21)
[2025-08-24T04:28:20.815Z] error: <httpProxy> Error calling https://}:8443/api/auth...
[2025-08-24T04:28:20.816Z] error: undefined
[2025-08-24T04:28:20.816Z] error: <httpProxy> [
  500,
  [Error: getaddrinfo EAI_AGAIN }] {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: '}'
  }
]
[2025-08-24T04:28:20.818Z] error: SyntaxError: "[object Object]" is not valid JSON
    at JSON.parse (<anonymous>)
    at c (/app/.next/server/pages/api/services/proxy.js:45:67782)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async y (/app/.next/server/pages/api/services/proxy.js:45:68527)
    at async X (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:18441)
    at async z.render (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:19237)
    at async NextNodeServer.runApi (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:671:9)
    at async NextNodeServer.handleCatchallRenderRequest (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:302:37)
    at async NextNodeServer.handleRequestImpl (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:899:17)
    at async invokeRender (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:237:21)
[2025-08-24T04:28:21.539Z] error: <httpProxy> Error calling https://}:8443/api/auth...
[2025-08-24T04:28:21.541Z] error: undefined
[2025-08-24T04:28:21.540Z] error: <httpProxy> [
  500,
  [Error: getaddrinfo EAI_AGAIN }] {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: '}'
  }
]
[2025-08-24T04:28:21.543Z] error: SyntaxError: "[object Object]" is not valid JSON
    at JSON.parse (<anonymous>)
    at c (/app/.next/server/pages/api/services/proxy.js:45:67782)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async y (/app/.next/server/pages/api/services/proxy.js:45:68527)
    at async X (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:18441)
    at async z.render (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:19237)
    at async NextNodeServer.runApi (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:671:9)
    at async NextNodeServer.handleCatchallRenderRequest (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:302:37)
    at async NextNodeServer.handleRequestImpl (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:899:17)
    at async invokeRender (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:237:21)
[2025-08-24T04:30:05.746Z] error: <httpProxy> Error calling https://}:8443/api/auth...
[2025-08-24T04:30:05.753Z] error: undefined
[2025-08-24T04:30:05.752Z] error: <httpProxy> [
  500,
  [Error: getaddrinfo EAI_AGAIN }] {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: '}'
  }
]
[2025-08-24T04:30:05.758Z] error: SyntaxError: "[object Object]" is not valid JSON
    at JSON.parse (<anonymous>)
    at c (/app/.next/server/pages/api/services/proxy.js:45:67782)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async y (/app/.next/server/pages/api/services/proxy.js:45:68527)
    at async X (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:18441)
    at async z.render (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:19237)
    at async NextNodeServer.runApi (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:671:9)
    at async NextNodeServer.handleCatchallRenderRequest (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:302:37)
    at async NextNodeServer.handleRequestImpl (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:899:17)
    at async invokeRender (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:237:21)
[2025-08-24T04:30:30.889Z] error: <httpProxy> Error calling https://}:8443/api/auth...
[2025-08-24T04:30:30.893Z] error: undefined
[2025-08-24T04:30:30.892Z] error: <httpProxy> [
  500,
  [Error: getaddrinfo EAI_AGAIN }] {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: '}'
  }
]
[2025-08-24T04:30:30.896Z] error: SyntaxError: "[object Object]" is not valid JSON
    at JSON.parse (<anonymous>)
    at c (/app/.next/server/pages/api/services/proxy.js:45:67782)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async y (/app/.next/server/pages/api/services/proxy.js:45:68527)
    at async X (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:18441)
    at async z.render (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:19237)
    at async NextNodeServer.runApi (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:671:9)
    at async NextNodeServer.handleCatchallRenderRequest (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:302:37)
    at async NextNodeServer.handleRequestImpl (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:899:17)
    at async invokeRender (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:237:21)
[2025-08-24T04:33:06.335Z] error: <httpProxy> Error calling https://}:8443/api/auth...
[2025-08-24T04:33:06.344Z] error: undefined
[2025-08-24T04:33:06.343Z] error: <httpProxy> [
  500,
  [Error: getaddrinfo EAI_AGAIN }] {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: '}'
  }
]
[2025-08-24T04:33:06.350Z] error: SyntaxError: "[object Object]" is not valid JSON
    at JSON.parse (<anonymous>)
    at c (/app/.next/server/pages/api/services/proxy.js:45:67782)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async y (/app/.next/server/pages/api/services/proxy.js:45:68527)
    at async X (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:18441)
    at async z.render (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:19237)
    at async NextNodeServer.runApi (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:671:9)
    at async NextNodeServer.handleCatchallRenderRequest (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:302:37)
    at async NextNodeServer.handleRequestImpl (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:899:17)
    at async invokeRender (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:237:21)
[2025-08-24T04:33:07.425Z] error: <httpProxy> Error calling https://}:8443/api/auth...
[2025-08-24T04:33:07.428Z] error: undefined
[2025-08-24T04:33:07.427Z] error: <httpProxy> [
  500,
  [Error: getaddrinfo EAI_AGAIN }] {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: '}'
  }
]
[2025-08-24T04:33:07.431Z] error: SyntaxError: "[object Object]" is not valid JSON
    at JSON.parse (<anonymous>)
    at c (/app/.next/server/pages/api/services/proxy.js:45:67782)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async y (/app/.next/server/pages/api/services/proxy.js:45:68527)
    at async X (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:18441)
    at async z.render (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:19237)
    at async NextNodeServer.runApi (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:671:9)
    at async NextNodeServer.handleCatchallRenderRequest (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:302:37)
    at async NextNodeServer.handleRequestImpl (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:899:17)
    at async invokeRender (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:237:21)
[2025-08-24T04:33:17.564Z] error: <httpProxy> Error calling https://}:8443/api/auth...
[2025-08-24T04:33:17.566Z] error: undefined
[2025-08-24T04:33:17.566Z] error: <httpProxy> [
  500,
  [Error: getaddrinfo EAI_AGAIN }] {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: '}'
  }
]
[2025-08-24T04:33:17.568Z] error: SyntaxError: "[object Object]" is not valid JSON
    at JSON.parse (<anonymous>)
    at c (/app/.next/server/pages/api/services/proxy.js:45:67782)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async y (/app/.next/server/pages/api/services/proxy.js:45:68527)
    at async X (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:18441)
    at async z.render (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:19237)
    at async NextNodeServer.runApi (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:671:9)
    at async NextNodeServer.handleCatchallRenderRequest (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:302:37)
    at async NextNodeServer.handleRequestImpl (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:899:17)
    at async invokeRender (/app/node_modules/.pnpm/next@15.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:237:21)
[2025-08-24T17:19:22.681Z] error: <credentialedProxyHandler> HTTP Error 401 calling http://192.168.0.209:11000/ocs/v2.php/apps/serverinfo/api/v1/info?format=json
[2025-08-24T17:19:23.205Z] error: <credentialedProxyHandler> HTTP Error 401 calling http://192.168.0.209:11000/ocs/v2.php/apps/serverinfo/api/v1/info?format=json
[2025-08-24T17:19:50.832Z] error: <credentialedProxyHandler> HTTP Error 401 calling http://192.168.0.209:11000/ocs/v2.php/apps/serverinfo/api/v1/info?format=json
[2025-08-24T17:21:15.935Z] error: <servicesProxy> YAMLException: tab characters must not be used in indentation (45:1)

 42 |         href: "https://nc.papat ...
 43 |         widget:
 44 |           type: nextcloud
 45 | →  url: https://https://nc.papa ...
------^
 46 |           username: "admin"
 47 |           password: "8122022bruh"
    at generateError (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:1273:10)
    at throwError (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:1277:9)
    at readBlockSequence (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2073:7)
    at composeNode (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2530:12)
    at readDocument (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2715:3)
    at loadDocuments (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2778:5)
    at Object.load$1 [as load] (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2804:19)
    at y (/app/.next/server/chunks/7325.js:1:4898)
    at async b (/app/.next/server/chunks/7325.js:1:7395)
    at async A (/app/.next/server/chunks/7325.js:1:7674)
[2025-08-24T17:21:15.937Z] error: <servicesProxy> YAMLException: tab characters must not be used in indentation (45:1)

 42 |         href: "https://nc.papat ...
 43 |         widget:
 44 |           type: nextcloud
 45 | →  url: https://https://nc.papa ...
------^
 46 |           username: "admin"
 47 |           password: "8122022bruh"
    at generateError (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:1273:10)
    at throwError (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:1277:9)
    at readBlockSequence (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2073:7)
    at composeNode (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2530:12)
    at readDocument (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2715:3)
    at loadDocuments (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2778:5)
    at Object.load$1 [as load] (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2804:19)
    at y (/app/.next/server/chunks/7325.js:1:4898)
    at async b (/app/.next/server/chunks/7325.js:1:7395)
    at async A (/app/.next/server/chunks/7325.js:1:7674)
[2025-08-24T17:21:15.939Z] error: <servicesProxy> YAMLException: tab characters must not be used in indentation (45:1)

 42 |         href: "https://nc.papat ...
 43 |         widget:
 44 |           type: nextcloud
 45 | →  url: https://https://nc.papa ...
------^
 46 |           username: "admin"
 47 |           password: "8122022bruh"
    at generateError (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:1273:10)
    at throwError (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:1277:9)
    at readBlockSequence (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2073:7)
    at composeNode (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2530:12)
    at readDocument (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2715:3)
    at loadDocuments (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2778:5)
    at Object.load$1 [as load] (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2804:19)
    at y (/app/.next/server/chunks/7325.js:1:4898)
    at async b (/app/.next/server/chunks/7325.js:1:7395)
    at async A (/app/.next/server/chunks/7325.js:1:7674)
[2025-08-24T17:21:15.951Z] error: Failed to load services.yaml, please check for errors
[2025-08-24T17:21:15.952Z] error: YAMLException: tab characters must not be used in indentation (45:1)

 42 |         href: "https://nc.papat ...
 43 |         widget:
 44 |           type: nextcloud
 45 | →  url: https://https://nc.papa ...
------^
 46 |           username: "admin"
 47 |           password: "8122022bruh"
[2025-08-24T17:21:15.966Z] error: Failed to load services.yaml, please check for errors
[2025-08-24T17:21:15.966Z] error: YAMLException: tab characters must not be used in indentation (45:1)

 42 |         href: "https://nc.papat ...
 43 |         widget:
 44 |           type: nextcloud
 45 | →  url: https://https://nc.papa ...
------^
 46 |           username: "admin"
 47 |           password: "8122022bruh"
[2025-08-24T17:21:16.156Z] error: Failed to load services.yaml, please check for errors
[2025-08-24T17:21:16.156Z] error: YAMLException: tab characters must not be used in indentation (45:1)

 42 |         href: "https://nc.papat ...
 43 |         widget:
 44 |           type: nextcloud
 45 | →  url: https://https://nc.papa ...
------^
 46 |           username: "admin"
 47 |           password: "8122022bruh"
[2025-08-24T17:21:17.884Z] error: Failed to load services.yaml, please check for errors
[2025-08-24T17:21:17.884Z] error: YAMLException: tab characters must not be used in indentation (45:1)

 42 |         href: "https://nc.papat ...
 43 |         widget:
 44 |           type: nextcloud
 45 | →  url: https://https://nc.papa ...
------^
 46 |           username: "admin"
 47 |           password: "8122022bruh"
[2025-08-24T17:21:42.280Z] error: Failed to load services.yaml, please check for errors
[2025-08-24T17:21:42.281Z] error: YAMLException: tab characters must not be used in indentation (45:1)

 42 |         href: "https://nc.papat ...
 43 |         widget:
 44 |           type: nextcloud
 45 | →  url: https://https://nc.papa ...
------^
 46 | →  username: "admin"
 47 |           password: "8122022bruh"
[2025-08-24T17:21:42.435Z] error: Failed to load services.yaml, please check for errors
[2025-08-24T17:21:42.435Z] error: YAMLException: tab characters must not be used in indentation (45:1)

 42 |         href: "https://nc.papat ...
 43 |         widget:
 44 |           type: nextcloud
 45 | →  url: https://https://nc.papa ...
------^
 46 | →  username: "admin"
 47 |           password: "8122022bruh"
[2025-08-24T17:21:43.570Z] error: Failed to load services.yaml, please check for errors
[2025-08-24T17:21:43.571Z] error: YAMLException: tab characters must not be used in indentation (45:1)

 42 |         href: "https://nc.papat ...
 43 |         widget:
 44 |           type: nextcloud
 45 | →  url: https://https://nc.papa ...
------^
 46 | →  username: "admin"
 47 |           password: "8122022bruh"
[2025-08-24T17:22:04.329Z] error: Failed to load services.yaml, please check for errors
[2025-08-24T17:22:04.329Z] error: YAMLException: tab characters must not be used in indentation (45:1)

 42 |         href: "https://nc.papat ...
 43 |         widget:
 44 |           type: nextcloud
 45 | →  url: https://https://nc.papa ...
------^
 46 | →  username: "admin"
 47 |           password: "8122022bruh"
[2025-08-24T17:22:40.063Z] error: Failed to load services.yaml, please check for errors
[2025-08-24T17:22:40.063Z] error: YAMLException: tab characters must not be used in indentation (46:1)

 43 |         widget:
 44 |           type: nextcloud
 45 |           url: https://https:// ...
 46 | →  username: "admin"
------^
 47 |           password: "8122022bruh"
 48 |         
[2025-08-24T17:22:40.214Z] error: Failed to load services.yaml, please check for errors
[2025-08-24T17:22:40.214Z] error: YAMLException: tab characters must not be used in indentation (46:1)

 43 |         widget:
 44 |           type: nextcloud
 45 |           url: https://https:// ...
 46 | →  username: "admin"
------^
 47 |           password: "8122022bruh"
 48 |         
[2025-08-24T17:23:19.783Z] error: Failed to load services.yaml, please check for errors
[2025-08-24T17:23:19.783Z] error: YAMLException: tab characters must not be used in indentation (45:1)

 42 |         href: "https://nc.papat ...
 43 |         widget:
 44 |           type: nextcloud
 45 | →  url: https://https://nc.papa ...
------^
 46 | →  username: "admin"
 47 |           password: "8122022bruh"
[2025-08-24T17:23:19.947Z] error: Failed to load services.yaml, please check for errors
[2025-08-24T17:23:19.947Z] error: YAMLException: tab characters must not be used in indentation (45:1)

 42 |         href: "https://nc.papat ...
 43 |         widget:
 44 |           type: nextcloud
 45 | →  url: https://https://nc.papa ...
------^
 46 | →  username: "admin"
 47 |           password: "8122022bruh"
[2025-08-24T17:23:20.930Z] error: Failed to load services.yaml, please check for errors
[2025-08-24T17:23:20.931Z] error: YAMLException: tab characters must not be used in indentation (45:1)

 42 |         href: "https://nc.papat ...
 43 |         widget:
 44 |           type: nextcloud
 45 | →  url: https://https://nc.papa ...
------^
 46 | →  username: "admin"
 47 |           password: "8122022bruh"
[2025-08-24T17:23:46.586Z] error: Failed to load services.yaml, please check for errors
[2025-08-24T17:23:46.586Z] error: YAMLException: tab characters must not be used in indentation (45:1)

 42 |         href: "https://nc.papat ...
 43 |         widget:
 44 |           type: nextcloud
 45 | →  url: https://https://nc.papa ...
------^
 46 | →  username: "admin"
 47 | →  password: "8122022bruh"
[2025-08-24T17:23:46.728Z] error: Failed to load services.yaml, please check for errors
[2025-08-24T17:23:46.728Z] error: YAMLException: tab characters must not be used in indentation (45:1)

 42 |         href: "https://nc.papat ...
 43 |         widget:
 44 |           type: nextcloud
 45 | →  url: https://https://nc.papa ...
------^
 46 | →  username: "admin"
 47 | →  password: "8122022bruh"
[2025-08-24T17:24:22.446Z] error: Failed to load services.yaml, please check for errors
[2025-08-24T17:24:22.446Z] error: YAMLException: tab characters must not be used in indentation (45:1)

 42 |         href: "https://nc.papat ...
 43 |         widget:
 44 |           type: nextcloud
 45 | →  url: https://https://nc.papa ...
------^
 46 | →  username: "admin"
 47 | →  password: "8122022bruh"
[2025-08-24T17:24:53.223Z] error: Failed to load services.yaml, please check for errors
[2025-08-24T17:24:53.224Z] error: YAMLException: tab characters must not be used in indentation (45:1)

 42 |         href: "https://nc.papat ...
 43 |         widget:
 44 |           type: nextcloud
 45 | →  url: https://https://nc.papa ...
------^
 46 | →  username: "admin"
 47 | →  password: "8122022bruh"
[2025-08-24T17:24:55.405Z] error: Failed to load services.yaml, please check for errors
[2025-08-24T17:24:55.405Z] error: YAMLException: tab characters must not be used in indentation (44:1)

 41 |         icon: nextcloud
 42 |         href: "https://nc.papat ...
 43 |         widget:
 44 | →  type: nextcloud
------^
 45 | →  url: https://https://nc.papa ...
 46 | →  username: "admin"
[2025-08-24T17:24:55.563Z] error: Failed to load services.yaml, please check for errors
[2025-08-24T17:24:55.563Z] error: YAMLException: tab characters must not be used in indentation (44:1)

 41 |         icon: nextcloud
 42 |         href: "https://nc.papat ...
 43 |         widget:
 44 | →  type: nextcloud
------^
 45 | →  url: https://https://nc.papa ...
 46 | →  username: "admin"
[2025-08-24T17:25:11.271Z] error: Failed to load services.yaml, please check for errors
[2025-08-24T17:25:11.271Z] error: YAMLException: tab characters must not be used in indentation (44:1)

 41 |         icon: nextcloud
 42 |         href: "https://nc.papat ...
 43 |         widget:
 44 | →  type: nextcloud
------^
 45 | →  url: https://https://nc.papa ...
 46 | →  username: "admin"
[2025-08-24T17:26:35.969Z] error: Failed to load services.yaml, please check for errors
[2025-08-24T17:26:35.969Z] error: YAMLException: tab characters must not be used in indentation (44:1)

 41 |         icon: nextcloud
 42 |         href: "https://nc.papat ...
 43 |         widget:
 44 | →  type: nextcloud
------^
 45 | →  url: https://https://nc.papa ...
 46 | →  username: "admin"
[2025-08-24T17:28:49.425Z] error: Failed to load services.yaml, please check for errors
[2025-08-24T17:28:49.425Z] error: YAMLException: tab characters must not be used in indentation (44:1)

 41 |         icon: nextcloud
 42 |         href: "https://nc.papat ...
 43 |         widget:
 44 | →  type: nextcloud
------^
 45 | →  url: https://https://nc.papa ...
 46 | →  username: "admin"
[2025-08-24T17:29:44.952Z] error: Failed to load services.yaml, please check for errors
[2025-08-24T17:29:44.952Z] error: YAMLException: tab characters must not be used in indentation (44:1)

 41 |         icon: nextcloud
 42 |         href: "https://nc.papat ...
 43 |         widget:
 44 | →  type: nextcloud
------^
 45 | →  url: https://https://nc.papa ...
 46 | →  username: "admin"
[2025-08-24T17:29:45.876Z] error: Failed to load services.yaml, please check for errors
[2025-08-24T17:29:45.876Z] error: YAMLException: tab characters must not be used in indentation (44:1)

 41 |         icon: nextcloud
 42 |         href: "https://nc.papat ...
 43 |         widget:
 44 | →  type: nextcloud
------^
 45 | →  url: https://https://nc.papa ...
 46 | →  username: "admin"
[2025-08-24T17:31:09.777Z] error: <credentialedProxyHandler> HTTP Error 401 calling http://192.168.0.209:11000/ocs/v2.php/apps/serverinfo/api/v1/info?format=json
[2025-08-24T17:31:10.105Z] error: <credentialedProxyHandler> HTTP Error 401 calling http://192.168.0.209:11000/ocs/v2.php/apps/serverinfo/api/v1/info?format=json
[2025-08-24T17:31:30.711Z] error: <httpProxy> Error calling http://https//nc.papatenko.org/ocs/v2.php/apps/serverinfo/api/v1/info...
[2025-08-24T17:31:30.720Z] error: <httpProxy> [
  500,
  [Error: getaddrinfo EAI_AGAIN https] {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: 'https'
  }
]
[2025-08-24T17:31:30.721Z] error: <credentialedProxyHandler> HTTP Error 500 calling http://https//nc.papatenko.org/ocs/v2.php/apps/serverinfo/api/v1/info?format=json
[2025-08-24T17:33:55.065Z] error: <httpProxy> Error calling https://nc.papatenko.org/ocs/v2.php/apps/serverinfo/api/v1/info...
[2025-08-24T17:33:55.069Z] error: <httpProxy> [
  500,
  Error: connect ETIMEDOUT 76.231.153.102:443
      at <unknown> (Error: connect ETIMEDOUT 76.231.153.102:443) {
    errno: -110,
    code: 'ETIMEDOUT',
    syscall: 'connect',
    address: '76.231.153.102',
    port: 443
  }
]
[2025-08-24T17:33:55.069Z] error: <credentialedProxyHandler> HTTP Error 500 calling https://nc.papatenko.org/ocs/v2.php/apps/serverinfo/api/v1/info?format=json
[2025-08-24T17:33:55.070Z] error: <httpProxy> Error calling https://nc.papatenko.org/ocs/v2.php/apps/serverinfo/api/v1/info...
[2025-08-24T17:33:55.072Z] error: <httpProxy> [
  500,
  Error: connect ETIMEDOUT 76.231.153.102:443
      at <unknown> (Error: connect ETIMEDOUT 76.231.153.102:443) {
    errno: -110,
    code: 'ETIMEDOUT',
    syscall: 'connect',
    address: '76.231.153.102',
    port: 443
  }
]
[2025-08-24T17:33:55.072Z] error: <credentialedProxyHandler> HTTP Error 500 calling https://nc.papatenko.org/ocs/v2.php/apps/serverinfo/api/v1/info?format=json
[2025-08-25T12:40:25.264Z] error: <httpProxy> Error calling http://192.168.0.133:11000/ocs/v2.php/apps/serverinfo/api/v1/info...
[2025-08-25T12:40:25.268Z] error: <httpProxy> [
  500,
  Error: connect ECONNREFUSED 192.168.0.133:11000
      at <unknown> (Error: connect ECONNREFUSED 192.168.0.133:11000) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '192.168.0.133',
    port: 11000
  }
]
[2025-08-25T12:40:25.268Z] error: <credentialedProxyHandler> HTTP Error 500 calling http://192.168.0.133:11000/ocs/v2.php/apps/serverinfo/api/v1/info?format=json
[2025-08-25T12:40:50.274Z] error: <httpProxy> Error calling http://192.168.0.133:11000/ocs/v2.php/apps/serverinfo/api/v1/info...
[2025-08-25T12:40:50.276Z] error: <httpProxy> [
  500,
  Error: connect ECONNREFUSED 192.168.0.133:11000
      at <unknown> (Error: connect ECONNREFUSED 192.168.0.133:11000) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '192.168.0.133',
    port: 11000
  }
]
[2025-08-25T12:40:50.276Z] error: <credentialedProxyHandler> HTTP Error 500 calling http://192.168.0.133:11000/ocs/v2.php/apps/serverinfo/api/v1/info?format=json
[2025-08-25T12:41:39.704Z] error: <httpProxy> Error calling http://192.168.0.133:11000/ocs/v2.php/apps/serverinfo/api/v1/info...
[2025-08-25T12:41:39.705Z] error: <httpProxy> [
  500,
  Error: connect ECONNREFUSED 192.168.0.133:11000
      at <unknown> (Error: connect ECONNREFUSED 192.168.0.133:11000) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '192.168.0.133',
    port: 11000
  }
]
[2025-08-25T12:41:39.705Z] error: <credentialedProxyHandler> HTTP Error 500 calling http://192.168.0.133:11000/ocs/v2.php/apps/serverinfo/api/v1/info?format=json
[2025-08-25T12:42:50.044Z] error: <credentialedProxyHandler> HTTP Error 401 calling http://192.168.0.209:11000/ocs/v2.php/apps/serverinfo/api/v1/info?format=json
[2025-08-25T12:42:50.411Z] error: <credentialedProxyHandler> HTTP Error 401 calling http://192.168.0.209:11000/ocs/v2.php/apps/serverinfo/api/v1/info?format=json
[2025-08-25T12:43:21.616Z] error: <credentialedProxyHandler> HTTP Error 401 calling http://192.168.0.209:11000/ocs/v2.php/apps/serverinfo/api/v1/info?format=json
[2025-08-25T12:43:44.988Z] error: <credentialedProxyHandler> HTTP Error 401 calling http://192.168.0.209:11000/ocs/v2.php/apps/serverinfo/api/v1/info?format=json
[2025-10-04T16:30:43.385Z] error: Failed to load services.yaml, please check for errors
[2025-10-04T16:30:43.386Z] error: YAMLException: tab characters must not be used in indentation (54:1)

 51 |         widget:
 52 |           type: immich
 53 |           url: http://192.168.0 ...
 54 | →  key: "m06Z2fJHC7vbBEvt0HE7uP ...
------^
 55 | →  version: 2
 56 |         
[2025-10-04T16:30:43.680Z] error: Failed to load services.yaml, please check for errors
[2025-10-04T16:30:43.681Z] error: YAMLException: tab characters must not be used in indentation (54:1)

 51 |         widget:
 52 |           type: immich
 53 |           url: http://192.168.0 ...
 54 | →  key: "m06Z2fJHC7vbBEvt0HE7uP ...
------^
 55 | →  version: 2
 56 |         
[2025-10-04T16:30:44.116Z] error: Failed to load services.yaml, please check for errors
[2025-10-04T16:30:44.116Z] error: YAMLException: tab characters must not be used in indentation (54:1)

 51 |         widget:
 52 |           type: immich
 53 |           url: http://192.168.0 ...
 54 | →  key: "m06Z2fJHC7vbBEvt0HE7uP ...
------^
 55 | →  version: 2
 56 |         
[2025-10-04T16:30:56.580Z] error: Failed to load services.yaml, please check for errors
[2025-10-04T16:30:56.580Z] error: YAMLException: tab characters must not be used in indentation (54:1)

 51 |         widget:
 52 |           type: immich
 53 |           url: http://192.168.0 ...
 54 | →  key: "m06Z2fJHC7vbBEvt0HE7uP ...
------^
 55 | →  version: 2
 56 |         
[2025-10-04T16:31:03.464Z] error: Failed to load services.yaml, please check for errors
[2025-10-04T16:31:03.465Z] error: YAMLException: tab characters must not be used in indentation (55:1)

 52 |           type: immich
 53 |           url: http://192.168.0 ...
 54 |           key: "m06Z2fJHC7vbBEv ...
 55 | →  version: 2
------^
 56 |         
 57 | - Websites:
[2025-10-04T16:31:03.728Z] error: Failed to load services.yaml, please check for errors
[2025-10-04T16:31:03.728Z] error: YAMLException: tab characters must not be used in indentation (55:1)

 52 |           type: immich
 53 |           url: http://192.168.0 ...
 54 |           key: "m06Z2fJHC7vbBEv ...
 55 | →  version: 2
------^
 56 |         
 57 | - Websites:
